// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUX3E4dcIFNh4Gl60AZYX5Jxdf_i_pn5U',
    appId: '1:74578111422:web:d254eb1e122bec786767ef',
    messagingSenderId: '74578111422',
    projectId: 'bd-parque-perufest',
    authDomain: 'bd-parque-perufest.firebaseapp.com',
    storageBucket: 'bd-parque-perufest.firebasestorage.app',
    measurementId: 'G-DQZQD5WJ5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtzu5u02SLpo_k9WTVjbG2bc8SS86_3dM',
    appId: '1:74578111422:android:8c2827a7b62a99dd6767ef',
    messagingSenderId: '74578111422',
    projectId: 'bd-parque-perufest',
    storageBucket: 'bd-parque-perufest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBioo05x7baxDKaCIVVqcmtO5E0NGmKRXk',
    appId: '1:74578111422:ios:853a98b2deb72d456767ef',
    messagingSenderId: '74578111422',
    projectId: 'bd-parque-perufest',
    storageBucket: 'bd-parque-perufest.firebasestorage.app',
    iosBundleId: 'com.example.appPerufest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBioo05x7baxDKaCIVVqcmtO5E0NGmKRXk',
    appId: '1:74578111422:ios:853a98b2deb72d456767ef',
    messagingSenderId: '74578111422',
    projectId: 'bd-parque-perufest',
    storageBucket: 'bd-parque-perufest.firebasestorage.app',
    iosBundleId: 'com.example.appPerufest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUX3E4dcIFNh4Gl60AZYX5Jxdf_i_pn5U',
    appId: '1:74578111422:web:37fa15c08c83f4cf6767ef',
    messagingSenderId: '74578111422',
    projectId: 'bd-parque-perufest',
    authDomain: 'bd-parque-perufest.firebaseapp.com',
    storageBucket: 'bd-parque-perufest.firebasestorage.app',
    measurementId: 'G-KC4PJ2CJLW',
  );
}
